# Generated by Django 3.1.1 on 2020-09-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('photo', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('month', models.CharField(choices=[('NORMAL', 'Normal'), ('PLATA', 'Plata'), ('ORO', 'Oro'), ('PLATINO', 'Platino')], default='NORMAL', max_length=7)),
            ],
        ),
    ]
