# Generated by Django 3.1.1 on 2020-09-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='month',
            new_name='type',
        ),
    ]
