# Generated by Django 3.1.1 on 2020-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_supply',
            field=models.DateTimeField(null=True),
        ),
    ]
